# version: '3'

services:
  scrp:
    build: .
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    restart: always

# if using npm, `docker network create metrominet` first https://nginxproxymanager.com/advanced-config/ 
networks:
  default:
    external: true
    name: metrominet
